### PR TITLE
Refactored some more rows in another file

### PR DESCRIPTION
**Pull request by HampusDahlin**
Changes were made.

### CODE REVIEW

**Comment by HampusDahlin** [comment]
Among other things I added some more semi-colons.

**Comment by Baloo1** [comment]
Yes is this code working? @HampusDahlin @Dr-Horv

**Comment by HampusDahlin** [comment]
Waiting for response from ops, please release.

**Comment by Baloo1** [comment]
alright they are on call

**Comment by HampusDahlin** [comment]
Works on my machine

**Pull request merged**
